//
//  PostDetailWireframe.swift
//  JSONPlaceholder Test
//
//  Created by Pedro Andres Villamil on 27/08/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class PostDetailWireframe: BaseWireframe {

    // MARK: - Private properties -

    // MARK: - Module setup -
    init(post: Post) {
        let moduleViewController = PostDetailViewController()
        super.init(viewController: moduleViewController)

        let interactor = PostDetailInteractor()
        let presenter = PostDetailPresenter(
            view: moduleViewController,
            interactor: interactor,
            wireframe: self,
            post: post
        )
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -
extension PostDetailWireframe: PostDetailWireframeInterface {
    
    func showAlert(witn message: String) {
        let alert = UIAlertController(title: "Error", message: message, preferredStyle: .alert)
        let action = UIAlertAction(title: "Understood", style: .destructive)
        alert.addAction(action)
        self.navigationController?.present(alert, animated: true) {() -> Void in }
    }
}
