//
//  PostDetailInteractor.swift
//  JSONPlaceholder Test
//
//  Created by Pedro Andres Villamil on 27/08/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class PostDetailInteractor {
    
}

// MARK: - Extensions -
extension PostDetailInteractor: PostDetailInteractorInterface {
    
    func getInfoUser(for userId: Int, completion: @escaping (UserInfoResult) -> Void) {
        let url = API.url(for: .users(userId: userId))
        ServiceManger.request(to: url) { (result:ServiceManger.CompletionResult<User>) in
            switch result {
            case .success(let response):
                completion(.success(response))
            case .failure(let error):
                completion(.failure(error))
            }
        }
    }
    
    func getComments(for postId: Int, completion: @escaping (CommentsResult) -> Void) {
        let url = API.url(for: .comments(id: postId))
        ServiceManger.request(to: url) { (result:ServiceManger.CompletionResult<Array<Comment>>) in
            switch result {
            case .success(let response):
                completion(.success(response))
            case .failure(let error):
                completion(.failure(error))
            }
        }
    }
    
    func getDetail(for postId: Int, completion: @escaping (DetailResult) -> Void) {
        let url = API.url(for: .postDetail(id: postId))
        ServiceManger.request(to: url) { (result:ServiceManger.CompletionResult<Post>) in
            switch result {
            case .success(let response):
                completion(.success(response))
            case .failure(let error):
                completion(.failure(error))
            }
        }
    }
}
