# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JSONPlaceholder Test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JSONPlaceholder Test

pod 'Alamofire'
pod 'SkeletonView'
pod 'Kingfisher'
pod 'lottie-ios'

  target 'JSONPlaceholder TestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JSONPlaceholder TestUITests' do
    # Pods for testing
  end

end
