//
//  PostsWireframe.swift
//  JSONPlaceholder Test
//
//  Created by Pedro Andres Villamil on 26/08/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class PostsWireframe: BaseWireframe {

    // MARK: - Private properties -

    // MARK: - Module setup -
    init() {
        let moduleViewController = PostsViewController()
        super.init(viewController: moduleViewController)

        let interactor = PostsInteractor()
        let presenter = PostsPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -
extension PostsWireframe: PostsWireframeInterface {

    func navigateToDetail(post: Post) {
        let detailPostWireframe = PostDetailWireframe(post: post)
        self.navigationController?.pushViewController(detailPostWireframe.viewController, animated: true)
    }
    
    func showAlert(witn message: String) {
        let alert = UIAlertController(title: "Error", message: message, preferredStyle: .alert)
        let action = UIAlertAction(title: "Understood", style: .destructive)
        alert.addAction(action)
        self.navigationController?.present(alert, animated: true) {() -> Void in }
    }
    
    func showShareAction(_ controller: UIActivityViewController, animated: Bool) {
        self.navigationController?.present(controller, animated: animated)
    }
    

}
