//
//  PostsInteractor.swift
//  JSONPlaceholder Test
//
//  Created by Pedro Andres Villamil on 26/08/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RealmSwift

final class PostsInteractor {
    
    let realm = try! Realm()
}

// MARK: - Extensions -
extension PostsInteractor: PostsInteractorInterface {
    
    func getPosts(id: Int, completion: @escaping (PostListResult) -> Void) {
        let url = API.url(for: .postListByUser(id: id))
        ServiceManger.request(to: url) { (result:ServiceManger.CompletionResult<List<Post>>) in
            switch result {
            case .success(let response):
                completion(.success(response))
            case .failure(let error):
                print(error)
                completion(.failure(error))
            }
        }
    }
    
    func getPersistedPost() -> List<Post> {
        let postList = Sesion.defaultUser(in: realm).postList
        return postList
    }
    
    func save(_ postList: List<Post>) {
        let me = Sesion.defaultUser(in: realm)
        do {
            try realm.write {
                postList.forEach { post in
                    if realm.object(ofType: Post.self, forPrimaryKey: post.id) == nil {
                        me.postList.insert(post, at: 0)
                    }
                }
            }
        }
        catch {
            print("[Realm] save error: \(error)")
        }
    }
    
    func deletePost(with id: Int) {
        guard let deletePost = realm.object(ofType: Post.self, forPrimaryKey: id) else { return }
        do {
            try realm.write { realm.delete(deletePost) }
        }
        catch {
            print("[Realm] delete error: \(error)")
        }
    }
    
    func deleteAllList() {
        let me = Sesion.defaultUser(in: realm)
        let list = me.postList
        do {
            try realm.write {
                list.forEach { post in
                    realm.delete(post)
                }
            }
        }
        catch {
            print("[Realm] delete error: \(error)")
        }
    }
}
