//
//  PostsInterfaces.swift
//  JSONPlaceholder Test
//
//  Created by Pedro Andres Villamil on 26/08/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RealmSwift

enum PostListResult {
    case success(List<Post>)
    case failure(Error)
}

protocol PostsWireframeInterface: WireframeInterface {
    func navigateToDetail(post: Post)
    func showAlert(witn message: String)
    func showShareAction(_ controller: UIActivityViewController, animated: Bool)
}

protocol PostsViewInterface: ViewInterface {
    func reloadView()
}

protocol PostsPresenterInterface: PresenterInterface {
    var numberOfItems: Int { get }
    var postNumber: Int { get }
    var emptyRequest: Bool { get }
    func didSelectItem(at indexPath: IndexPath)
    func loadNextPage()
    func item(at indexPath: IndexPath) -> PostCellViewModel?
    func deleteIteam(at indexPath: IndexPath)
    func toggleFavoriteInPost(at indexPath: IndexPath)
    func deleteAllList()
    func refreshList()
    func showShareAction(_ controller: UIActivityViewController, animated: Bool) 
}

protocol PostsInteractorInterface: InteractorInterface {
    func getPosts(id: Int, completion: @escaping (PostListResult) -> Void)
    func getPersistedPost() -> List<Post>
    func save(_ postList: List<Post>)
    func deletePost(with id: Int)
    func deleteAllList()
}
